config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :users, only: :show
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '10代' },
    { id: 2, name: '20代' },
    { id: 3, name: '30代' },
    { id: 4, name: '40代〜' },
    { id: 5, name: '60代〜 ' }
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :sex
  belongs_to :age
  belongs_to :style
  belongs_to :purpose

  with_options presence: true do
    validates :title
    validates :workout
    validates :meal
  end

  with_options numericality: { other_than: 0 } do
    validates :sex_id
    validates :age_id
    validates :style_id
    validates :purpose_id
  end
end

app/models/pupose.rb
class Purpose < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ダイエット' },
    { id: 2, name: '筋力アップ' },
    { id: 3, name: '健康維持' },
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/purpose.rb
class Purpose < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ダイエット' },
    { id: 2, name: '筋力アップ' },
    { id: 3, name: '健康維持' }
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' }
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/style.rb
class Style < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ジムトレーニング' },
    { id: 2, name: '自重トレーニング' }
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :search_product, only: [:index, :search, :show]
  def index
    @posts = Post.includes(:user).order('created_at DESC')
    set_post_column
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
      flash[:notice] = '投稿が保存されました'
    else
      render :new
      flash[:alert] = '投稿に失敗しました'
    end
  end

  def show
    set_post_column
  end

  def destroy
    if @post.user_id = current_user.id
      @post.destroy
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
      flash[:notice] = '投稿が編集されました'
    else
      render :edit
      flash[:alert] = '編集に失敗しました'
    end
  end

  def search
    @results = @p.result
  end

  private

  def post_params
    params.require(:post).permit(:title, :workout, :meal, :sex_id, :age_id, :style_id,
                                 :purpose_id).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def search_product
    @p = Post.ransack(params[:q])
  end

  def set_post_column
    @post_sex = Post.select('sex_id').distinct
    @post_style = Post.select('style_id').distinct
    @post_purpose = Post.select('purpose_id').distinct
    @post_age = Post.select('age_id').distinct
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <meta name="viewport" content="width=device-width, initial-scale=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper">
       <%= render 'partial/navbar' if current_user %>
       <% if flash[:notice] %>
         <div class="alert alert-info"><%= flash[:notice] %></div>
       <% end %>
       <% if flash[:alert] %>
         <div class="alert alert-danger"><%= flash[:alert] %></div>
       <% end %>
    <div class="container">
     <%= yield %>
    </div>
     <%= render 'partial/footer' %>
  </div>
  </body>
</html>

app/views/partial/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © DietApp
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-md-auto align-items-center">
            <li>
              <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
            </li>
            <li>
              <%= link_to current_user.nickname, user_path(current_user), class: "profile-nickname" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/posts/edit.html.erb
<div class="posts-sell-contents">

  <div class="posts-sell-main">
    <h2 class="posts-sell-title">情報を修正を入力</h2>
    <%= form_with model: @post, local: true do |f| %>

  <%= render 'partial/error_messages', model: f.object %>

    <div class="new-posts">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          運動内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :workout, class:"posts-text", id:"item-info", placeholder:"やるべき運動内容（必須 1,000文字まで）例）週3回ジムでの筋トレ,ベンチプレス10回3セット、スクワット10回3セット、チンニング10回3セット、腹筋30回3セット" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="posts-explain">
        <div class="weight-bold-text">
          食事内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :meal, class:"posts-text", id:"item-info", placeholder:"毎日の食事内容（必須 1,000文字まで）例）朝：おにぎり1個,牛肉200g,お味噌汁 昼: おにぎり1個,鳥胸肉200g,野菜　夜: おにぎり1個,脂身の少ない肉200g,野菜　間食: ナッツ、プロテイン"  ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="posts-detail">
      <div class="weight-bold-text">詳細情報</div>
      <div class="form">
        <div class="weight-bold-text">
          性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"post-sex"}) %>
        <div class="weight-bold-text">
          年代
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"select-box", id:"post-age"}) %>
        <div class="weight-bold-text">
          運動スタイル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:style_id, Style.all, :id, :name, {}, {class:"select-box", id:"post-style"}) %>
        <div class="weight-bold-text">
          目的
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:purpose_id, Purpose.all, :id, :name, {}, {class:"select-box", id:"post-purpose"}) %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to '詳細ページへもどる',post_path(@post.id) , class:"back-btn" %>
    </div>

  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class='main'>
<div class='title-contents'>
    <h2 class='service-title'>
    KENSAKUN
    </h2>
    <p class='service-explain'>
      自分に合わせて情報検索
    </p>
  </div>
<div class="post-search-contents"> 
  <h2 class='titles'>
    検索欄
  </h2>
  <%= search_form_for @p, url: search_posts_path do |f| %>
      <%= f.label :sex_id_eq, '対象性別　1:男性　2:女性：' %>
      <%= f.collection_select :sex_id_eq, @post_sex, :sex_id, :sex_id, include_blank: '指定なし'%>
      <br>
      <%= f.label :age_id_eq, '対象年齢　1: 10代　2: 20代　3: 30代　4: 40代~　5: 60代~：' %>
      <%= f.collection_select :age_id_eq, @post_age, :age_id, :age_id, include_blank: '指定なし'%>
     <br>
      <%= f.label :style_id_eq, '運動スタイル　1:ジムトレ 2:家トレ：' %>
      <%= f.collection_select :style_id_eq, @post_style, :style_id, :style_id, include_blank: '指定なし'%>
     <br>
      <%= f.label :purpose_id_eq, '目的　1:ダイエット 2:筋力アップ 3:健康維持：' %>
      <%= f.collection_select :purpose_id_eq, @post_purpose, :purpose_id, :purpose_id, include_blank: '指定なし'%>
      <br>
      <%= f.submit '検索', class:"search-btn" %>
   <% end %>
</div>
  

  <div class='post-contents'>
    <div class="subtitle" >
      投稿一覧
    </div>
    <ul class='post-lists'>
    <% @posts.each do |post|%>
      <li class='list'>
      <%= link_to post_path(post.id), method: :get do %>
        <div class='post-info'>
          <h3 class='post-name'>
            <%= post.title %>
          </h3>
          <div class='post-price'>
            <span><%= post.sex.name %><br><%= post.purpose.name %></span>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% if @posts.length == 0 %>
      <li class='list'>
        <div class='post-info'>
          <h3 class='post-name'>
            投稿がありません
          </h3>
        </div>
      </li>
      <% end %>

    </ul>
  </div>

</div>

app/views/posts/new.html.erb
<%= form_with model: @post, local: true do |f| %>
<%= render 'partial/error_messages', model: f.object %>
<div class="posts-sell-contents">
  <div class="posts-sell-main">
    <h2 class="posts-sell-title">情報を入力</h2>
    <div class="new-posts">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"post-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          運動内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :workout, class:"posts-text", id:"post-info", placeholder:"やるべき運動内容（必須 1,000文字まで）例）週3回ジムでの筋トレ,ベンチプレス10回3セット、スクワット10回3セット、チンニング10回3セット、腹筋30回3セット" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="posts-explain">
        <div class="weight-bold-text">
          食事内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :meal, class:"posts-text", id:"post-info", placeholder:"毎日の食事内容（必須 1,000文字まで）例）朝：おにぎり1個,牛肉200g,お味噌汁 昼: おにぎり1個,鳥胸肉200g,野菜　夜: おにぎり1個,脂身の少ない肉200g,野菜　間食: ナッツ、プロテイン"  ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="posts-detail">
      <div class="weight-bold-text">詳細情報</div>
      <div class="form">
        <div class="weight-bold-text">
          性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"post-sex"}) %>
        <div class="weight-bold-text">
          年代
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"select-box", id:"post-age"}) %>
        <div class="weight-bold-text">
          運動スタイル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:style_id, Style.all, :id, :name, {}, {class:"select-box", id:"post-style"}) %>
        <div class="weight-bold-text">
          目的
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:purpose_id, Purpose.all, :id, :name, {}, {class:"select-box", id:"post-purpose"}) %>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "投稿", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/search.html.erb
<div class='post-contents'>
<h1>
  検索結果
</h1>
<ul class='post-lists'>
<% if @results.length !=0 %>
  <% @results.each do |post| %>
  <li class='list'>
      <%= link_to post_path(post.id), method: :get do %>
        <div class='post-info'>
          <h3 class='post-name'>
            <%= post.title %>
          </h3>
          <div class='post-price'>
            <span><%= post.sex.name %><br><%= post.purpose.name %></span>
          </div>
        </div>
        <% end %>
  <% end %>
<% else %>
  該当する投稿はありません
<% end %>
<%= link_to 'トップページへ戻る', root_path %>
</ul>
</div>

app/views/posts/show.html.erb
<div class="post-show">
  <div class="post-box">
    <h2 class="name">
      <%= @post.title %>
    </h2>
     <div class="post-explain-box">
      <span><%= "詳細情報" %></span>
    </div>
    <table class="detail-table">
      <tbody>
      <tr>
          <th class="detail-post">運動内容</th>
          <td class="detail-value"><%= @post.workout %></td>
        </tr>
        <tr>
          <th class="detail-post">食事内容</th>
          <td class="detail-value"><%= @post.meal %></td>
        </tr>
        <tr>
          <th class="detail-post">対象性別</th>
          <td class="detail-value"><%= @post.sex.name %></td>
        </tr>
        <tr>
          <th class="detail-post">対象年齢</th>
          <td class="detail-value"><%= @post.age.name %></td>
        </tr>
        <tr>
          <th class="detail-post">運動スタイル</th>
          <td class="detail-value"><%= @post.style.name %></td>
        </tr>
        <tr>
          <th class="detail-post">目的</th>
          <td class="detail-value"><%= @post.purpose.name %></td>
        </tr>
        <tr>
          <th class="detail-post">投稿者名</th>
          <td class="detail-value"><%= @post.user.nickname %></td>
        </tr>
      </tbody>
    </table>

    <% if user_signed_in? %>
    <% if current_user.id == @post.user.id %>
    <%= link_to "情報編集", edit_post_path(@post.id), method: :get, class: "post-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", post_path(@post.id), method: :delete, class:"post-destroy" %>
    <% end %>
    <% end %>

</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <h1><%= @user.nickname %></h1>
        <% if @user == current_user %>
          <%= link_to "", class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>
        

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="row">
          <p>
            <%= @user.email %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>